### ISSUE TITLE
Dijkstra Algorithm

### ISSUE THREAD

**Issue by CODER-AsHuToSh** [am-iitian/graph_algorithms#1]
Can anyone add Dijkstra Algorithm?

**Comment by CODER-AsHuToSh** [comment]
Can you assign me this issue?

**Comment by ashutosh-gupta2111** [comment]
@ashutosh-gupta2111 am assigning #1 issue to you.

**Comment by am-iitian** [comment]
@ashutosh-gupta2111 am assigning #1 issue to you.

**Comment by am-iitian** [comment]
thanks @ashutosh-gupta2111 for contributing, closing this issue.
